hash-format = "sha256"

[[files]]
file = "mods/abnormals-delight.pw.toml"
hash = "26ebcc24106ded2bec288547aba566a6ca92fd685c23d1a6221765f6f3f3e5c9"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "eed03a69cacac3a826fc07806ad069b0ae605fefcedab2b2b8fcfa060eb60ebb"
metafile = true

[[files]]
file = "mods/alexs-caves-delight-(-farmers-delight-alexs-caves-add-on).pw.toml"
hash = "8e8707ea278658a5fb3c6a4733377e84161d5b07eaaf14e263df8d1c10f27343"
metafile = true

[[files]]
file = "mods/another-furniture.pw.toml"
hash = "90b4a61d7ee6099dc34cf85f099299293401b87fc8f3ca07ed59262c1c63c5a5"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5e9edd1fd2395f14a0c8a4acbdbdd61e1047be1f0033deb3140d2ce0d093e9d8"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "e11ddca37c00c8cdf8ee89c7b59df544f50966d2d6c5b016916f023afb98c02e"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "fec49033058ced91f7668d4e305e599f5527501ef37c1f30f96d8927d6202d32"
metafile = true

[[files]]
file = "mods/blueprint.pw.toml"
hash = "90fc66d49d29c1b1a5b14c5d571d628c6853f7f0519b04e74e14399c75cd08c6"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "02062a6b61e230e7debaf1c03d5e1e7203e427588fceb9f3d6ef8cad8062397e"
metafile = true

[[files]]
file = "mods/builders-delight.pw.toml"
hash = "dd3e909b4a5c69bf083e71beb203ec33b59ba9121280382bd7cd34dbbab45ee8"
metafile = true

[[files]]
file = "mods/chefs-delight.pw.toml"
hash = "eea01c16f108225646d8d7775eed0f07545461ddcd56ec304b3f8473d89bbc18"
metafile = true

[[files]]
file = "mods/chimes.pw.toml"
hash = "5858099ebe457e69e964e9a1c25b5267fdade0f7cc385ec3aea35092655b4c84"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "b0732421ae2999d558a7b70a11fa86a93738ca33f6f3ec343017796df9c47d9c"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "c7ac7f84731a0ca1fefb3491c3f65c2767afd4be207e094fcb65c4cea99c9549"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "903352ffbd84d4b95fed905893f4715d9c3f88ec9fff6fb06f6e359e0b839dc3"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "853df4ab2418f347cbb1e3b4ca6c82b2a517a8e4e8ccabcd42c27e3496707a32"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "aab86d52c9896cfcf7c0635c3c897c3dd190de84e3be9eeb726a22c5a61602ed"
metafile = true

[[files]]
file = "mods/create-cafe.pw.toml"
hash = "c01e6f68aeec0f8ac8299d2fac9a624075dd759e9ccf7c011729c24019422f92"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "0b69f772db857977d0e70bad04d4a8112f0963074ca07258efb44d2d3e5f4578"
metafile = true

[[files]]
file = "mods/create-chipped.pw.toml"
hash = "c8f77b841f628386aabb46e087b43ebf87b1bd70626eaaae194243851ece9dab"
metafile = true

[[files]]
file = "mods/create-confectionery.pw.toml"
hash = "8845c6e549e63cef58e420a081b87e1db4230ea02efc835c74b8dab37e183148"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "a6996b00e7652e93ec5d8d1b80e29af50129fbce103c582711e2f6dff0837fce"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "87be52b8aaa9864eab1ec2df8c862cd01a084989b07c4cdbfaa21c57a9a778a6"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "c670ae9055f10dafb61fe340583c361f4c41ed45671c9440bae1f0696b47252a"
metafile = true

[[files]]
file = "mods/create-mechanical-chicken.pw.toml"
hash = "defa6cc58a8f4c0db7df8505eaea45c071c06eed882afc708a52221eadce2a09"
metafile = true

[[files]]
file = "mods/create-metallurgy.pw.toml"
hash = "2ea783e4b95304d840853f8aa0b0de6601c214af705b550cb0669ef9e6c91f53"
metafile = true

[[files]]
file = "mods/create-mob-spawners.pw.toml"
hash = "0a52d755d0facf65ed651b7b42f3240e3e93b8cc0cd89ff96941e413001a9195"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "e2f6ea99d54ae392b33fb1911f9a3861cb43537435198f08df58a7c904a43883"
metafile = true

[[files]]
file = "mods/create-optical.pw.toml"
hash = "7dca9a704bfe6bec63cf4b5d5274b318109e43ca915b540fde07a748fa2f1bac"
metafile = true

[[files]]
file = "mods/create-recycling.pw.toml"
hash = "bdf77b87f521c9617f772e39f72bb90482d635ee457341526fbb76abbb175789"
metafile = true

[[files]]
file = "mods/create-snt-reforged.pw.toml"
hash = "260cbb9d29139d14a9ba3ff990faec4a7063a34d012d314d9cbd3f89f42a5d97"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "b13bad02617c5c0b39dede935d46bbf9755e66581087254372a12364b75df2b9"
metafile = true

[[files]]
file = "mods/create-utilities.pw.toml"
hash = "448ef7a4a3d83079e682a55d10e41f8ae5df430043b60dd7061d3268e72d8b35"
metafile = true

[[files]]
file = "mods/create-winery.pw.toml"
hash = "5d85af304e479830d25dc45db5d9fc1dcd99148ed4638251ac2f11c22cbec268"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "fb5c251cf4997fa65ca043bab7c9ecbd02e108031584a3e26276b77d212de23c"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "e6d1f36e9e0193fe410d136e0cda8a7f6dbbc809c0644f06a601bddf5b38a395"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "2eb26b157c4159bfeff6a00147afa35284397d558f84b55367d1a41064d7456a"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "1315cd56b0b4a5b3d53374cebf4f1f3cd0546b05058740847bd226c1d1ccab39"
metafile = true

[[files]]
file = "mods/delightful.pw.toml"
hash = "c79e3a922498c4dbbecfa90c81534faf102ca9285bea9f10aef43b5994780739"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "b67251b53eb4685d349bda68fde30b021e99900fe4d445e6c0f3e9fa0a908580"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "25d3f272639cef595de126a2c51faff793dc03bcde63ef060e1277c315583ce7"
metafile = true

[[files]]
file = "mods/every-compat.pw.toml"
hash = "dde582606c9a0d392457f053abc1b81ba6851952a88ef8d0e208bdfb9b419f29"
metafile = true

[[files]]
file = "mods/fairy-lights.pw.toml"
hash = "eeca094798607a0393a5ec261a0f3298e20fa74b0daa879951aec47c2c7fe64b"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "9f2ffb0d4c65fcb2a96878287a7119459b9d0637c395e5097d691416690d6563"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "902bac905b93271f02bd0951a22bac06a3da24f5c237fcaeb469e14a7679e508"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "48e2fa3089beed20a23ff2d171259768b2080ab0ff196841a18eb93c38e1c8b2"
metafile = true

[[files]]
file = "mods/ftb-xmod-compat.pw.toml"
hash = "39e65bf3c47517cdb2f9b4b49c6632dd56db797744faaf8b1a3726b1b95aacb4"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "e4bf02e4f4d64894c96ef07b68762f90c138bb202665bc6b377e000c715f2efd"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "30fe947e95d8da536ea4ad3c959f07cc504dd739ea530f7f4187ac08f4afcbc0"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "db495b3ac268709a2ba673bfe220b10257fb7dae549f94bfbd539617d571f131"
metafile = true

[[files]]
file = "mods/idas.pw.toml"
hash = "675609a9fb0ed19788e460191f2fba6279e56e63d702c3d506e6e1a1c0c9ffb0"
metafile = true

[[files]]
file = "mods/integrated-api.pw.toml"
hash = "73f0fb77d1827b8571a4a17f39920b813c356fe2c8647ae1195de50792e5bc7c"
metafile = true

[[files]]
file = "mods/integrated-cataclysm.pw.toml"
hash = "f27119e6d95e46b4943ec7af13ff5a68f8344c6f0344e86a22fe686512c754f7"
metafile = true

[[files]]
file = "mods/integrated-stronghold.pw.toml"
hash = "6a3e8217b2009309ea78ab26a1cbaf6ce53e154846efab841c61467426d27562"
metafile = true

[[files]]
file = "mods/integrated-villages.pw.toml"
hash = "4c370e8ae8dcd19e0cb8f59c88d054c1d7f9cb3591cbf00a7970505bc9e09480"
metafile = true

[[files]]
file = "mods/item-filters.pw.toml"
hash = "6f92d6a906fe5d960b53dc83e0060edfb2604f8deb4b38d25f7f66525966f7ad"
metafile = true

[[files]]
file = "mods/lendercataclysm.pw.toml"
hash = "75199fa3b762c5aa781e3cb2aab7779d19128b2a1c5b15798d5e613df8d16573"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
hash = "60af8798dbf3e300a5af44125595afcd5d1e70072448444156364f222cc03e98"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "97b807fbcaa59fd13ffdfd1428a2484d7c320f94af9ffda992ee9be9beba0286"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "c6f0ce3cbe75d1fa738142b797549087b4e119a54223222117c962fb809c9e06"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "f83b253ca6a8e6f2f847952704da0e1fb00e65cbb10b7c9cb15d1a1780618da0"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml"
hash = "204d6d88b0ea0977b1b878ebf7d52c236aec5c603f115f80af3710283d058f97"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
hash = "d83920425903922fce4ca45c07622f1d307b0f47f21b2f21899c426feedce8b7"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "4ab869d8784f4ac318b5c92fa3d9e65f997352b8b57f34b409ca6f171637f0fe"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "4dd7038889da90e145f9d074bec64a61aaae12dc57c875aa7ad99b8b2e07979b"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "4eb683644ee4e38e00b06df946b71ad8fedaa860fcabbd91ec6ceb71c65b8d81"
metafile = true

[[files]]
file = "mods/rechiseled-create.pw.toml"
hash = "24e203f4cadbbbda2d3641ff33e60e2de7f1ef8d8130b6a69e18cedd9f89ae89"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
hash = "eec149bebb07dd47cbe131a73dfc6f118539b9e70dc7d7026dccf5bc867224e8"
metafile = true

[[files]]
file = "mods/regions-unexplored.pw.toml"
hash = "cc64ca541c4710726dc3fa4b283b1260cfb2d3ff8d1784f80e0180d248c35688"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "5c07edd0c8fe82e85efd6c027476ba54cf98291526803b74614c3436292e4ab6"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "f9834af674abc824248bedb2e490ab426cff92b036cb20413cbbacd67ec6f5e3"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "f49c7302f7a044aae67740fac3a7558ca2f26b3a89a69a3940d516a40e3b75b7"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-create-integration.pw.toml"
hash = "0e6b84398cd76ad10e251af670b7b47fa5d320f15a5b0d67b52bef12dd20d41a"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "1d2b910e56a0abafd1230b076b519d48277e42d567ae82fac7ab2cfba37f4556"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "2462cbdca19b14aee41ee417c6e673e47724d96cedb88001395d67b76f523815"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "0be4976227df8e261fd362889bf8e85b93e224d1b1c3cd2a11b73a9de3b64083"
metafile = true

[[files]]
file = "mods/storage-delight.pw.toml"
hash = "39e70e87ab2c956af3ff5d2e3723adb2d3ed32405dd65b404fc5f2e38b2d9e18"
metafile = true

[[files]]
file = "mods/structure-essentials-forge-fabric.pw.toml"
hash = "8f907c02b348e25358cf2bca42e9105b9b6103f670bf36432da6752e2c8806db"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "1cf9cb3955b075664ea4fba13b47fe7160975740a28864983aebd53d39c1946e"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "042bedf190bfa3c51606a76c39eff873c772d570d44f0791a4db565d9967ff8b"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "80cc9e9ba6f53fa0a165c8ceb24d295eac471ecbb64f2b7711f1751264d96c1f"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "14117b94c456598c9acece143c7a0da3cf56d13182d035a74a2da8a52dd19cbd"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "131c818cca79586fdca0535062a63581e7c438efd108be4403ab8faea92e6368"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "152c6732da180e958fb29f492bae2e468d4dfd423ce4d3d0d31ef31c2eec6c61"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "c35112cced2eec8e5782c5c4327ae31bce16cc1356c75e52000053e890e0f0c1"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "302d69d833264022aa7ff781dbcde7f60f3c9e3021881b29f6f59223c36579c8"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "41aa01e9d0507d3131eb5fd2f6d8f2b7c54237e30a94e2a3bf6f52915cb8a688"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "05f825a655bc94af6ab592d13c396b60c818cfc65ff2528e206e7a40a180e210"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "60511ad5628ed8e45a552de171c3330bdcdbd5f86f7047e26b505b7a8c824a47"
metafile = true

[[files]]
file = "mods/yungs-cave-biomes.pw.toml"
hash = "1b458a12e9c076ae870dfaa64aaede89c7e6d18fe0c915d89b349a0af4250253"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
hash = "a9421a7a29ac8ee6e0598ea20025ad2c30e6198b796324184600621743437c91"
metafile = true

[[files]]
file = "resourcepacks/every-compat-ultimate.pw.toml"
hash = "b091407bb6850c79fb9046afbea0235e930ce9896e7ea43f7de20e1b325736e0"
metafile = true
