name = "Timeglass"
author = "David Roush"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d6f8fc8afafbc78258e77da88b1595d8e725b8bc318b7b725519f44bdae7718"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
