name = "Timeglass"
author = "David Roush"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90a1bae7e3374ff27d1557b352d08ca0564923ac3c443e16ae3a71b8e8cc783c"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
