name = "Timeglass"
author = "David Roush"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d2281925436a2c19258379c5d7a6f34b4aff6fb7a203cc21eb49807deaab308"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
