name = "Timeglass"
author = "David Roush"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da8cedba0e2604465cc6a33bb304ee202a280055b2f19a7212a58391fd5b26d7"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
