name = "Timeglass"
author = "David Roush"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e08381e55ace7de58eb2e180203f06994dd641a0b3abac2256d052684751844"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
