name = "Timeglass"
author = "David Roush"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36e385162de56c80258a31a26ef518be3422117732c271ba71349531f2f50530"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
