name = "Timeglass"
author = "David Roush"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "520245c5ffe82512541212f6045a60a24a51caf6e73f7a68068c1e5b4fea1266"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
