name = "Timeglass"
author = "David Roush"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "457b81fcce82ddf88f31e7f3471de43dc4dff0106d4fef0e407f6324c6412a7f"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
