name = "Timeglass"
author = "David Roush"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "286e9a89cdeb515d108ae86df2d61fdf35af5bead9fbb90a4c5fd3087f772115"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
