name = "Timeglass"
author = "David Roush"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf3b7d84fc761652043eda1a8562e5543d94ca12d3a521473c2c9dfc324477fb"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
