name = "Timeglass"
author = "David Roush"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b04a7b4cabb332252bbdc52a55bce590451884690a14fd7997feaf3a0942e71e"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
