name = "Timeglass"
author = "David Roush"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fba05ae09e5dad016a2078e5199d0828231fa5c66545edac3bdb55ac141e4bd1"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
