name = "Timeglass"
author = "David Roush"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70a8eff4b6958f8ddf2805b7c2e484bb0ec96f48fd41e91a47dd36924350e2cd"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
